name: chord_lang
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command: ^1.0.7
  flutter_notemus: ^2.8.1
  flutter_switch: ^0.3.2
  provider: ^6.1.5+1
  simple_sheet_music: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

msix_config:
  display_name: M#
  #publisher_display_name: Music Sharp
  #identity_name: musicsharp.suite.flutterapp
  msix_version: 1.0.0.0
  logo_path: C:\Users\Christian\GitHub\ChordTraining\chord_lang\assets\images\sharp-image.png
  #capabilities:
